make:
	g++ -std=c++17 treread.cpp xtre.cpp -o wctre

windows:
	x86_64-w64-mingw32-c++-win32 -std=c++17 -fPIC -static -static-libgcc -static-libstdc++ treread.cpp xtre.cpp -o wctre.exe

clean:
	rm wctre
