name: goreleaser

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    ubuntubuild:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Build
                run: |
                  sudo apt-get install -y build-essential gcc mingw-w64-tools zip gzip tar g++-mingw-w64-x86-64
                  cd wctre
                  make make windows
                  tar czf linux-amd64.tar.gz wctre
                  zip c windows-amd64.zip wctre.exe
            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: wctre/linux-amd64.tar.gz
            - uses: shogo82148/actions-upload-release-asset@v1
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: wctre/windows-amd64.zip
